run:
  timeout: 5m
  go: '1.26'

env:
  - GOEXPERIMENT=simd

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gosimple

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-use-default: false
