version: "3"

vars:
  GO: go1.26rc2
  WORK_DIR: '{{.WORK_DIR | default "/work"}}'
  MODELS_DIR: '{{.MODELS_DIR | default (joinPath .WORK_DIR "models")}}'
  MCF_DIR: '{{.MCF_DIR | default (joinPath .MODELS_DIR "mcf")}}'
  RAW_MODELS_DIR: '{{.RAW_MODELS_DIR | default (joinPath .MODELS_DIR "raw")}}'
  BUILD_FLAGS: '-ldflags="-w -s" -trimpath'
  BINARY_NAME: '{{if .CUDA}}mantle_cuda{{else}}mantle{{end}}'
  BUILD_TAGS: '{{if .CUDA}}-tags cuda{{end}}'
  CUDA_HOME_RESOLVED:
    sh: |
      if [ -n "$CUDA_HOME" ]; then
        printf "%s" "$CUDA_HOME"
      elif command -v nvcc >/dev/null 2>&1; then
        dirname "$(dirname "$(readlink -f "$(command -v nvcc)")")"
      else
        printf ""
      fi
  CUDA_LIBDIR:
    sh: |
      if [ -n "$CUDA_HOME" ]; then
        printf "%s/lib64" "$CUDA_HOME"
      elif command -v nvcc >/dev/null 2>&1; then
        home="$(dirname "$(dirname "$(readlink -f "$(command -v nvcc)")")")"
        printf "%s/lib64" "$home"
      else
        printf ""
      fi

env:
  ENV: '{{.ENV | default "development"}}'
  GOEXPERIMENT: "simd"
  MANTLE_MODELS_DIR: '{{.MCF_DIR}}'
  MANTLE_PACK_OUT_DIR: '{{.MCF_DIR}}'

dotenv: 
  - .env.local
  - .env.{{.ENV}}
  - example.env

tasks:
  default:
    cmds:
      - "task: build"

  setup:
    desc: Install Go 1.26rc2 toolchain
    cmds:
      - "go install golang.org/dl/go1.26rc2@latest"
      - "go1.26rc2 download"
      - "go1.26rc2 version"
    status:
      - "which go1.26rc2"

  build:
    desc: Build the mantle binary (use CUDA=1 for cuda backend)
    cmds:
      - '{{if .CUDA}}CGO_LDFLAGS="-L{{.CUDA_LIBDIR}}" LD_LIBRARY_PATH="{{.CUDA_LIBDIR}}:$LD_LIBRARY_PATH" {{end}}{{.GO}} build {{.BUILD_FLAGS}} {{.BUILD_TAGS}} -o bin/{{.BINARY_NAME}} ./cmd/mantle'
      - 'echo "Build Complete: bin/{{.BINARY_NAME}}"'
    sources:
      - cmd/mantle/**/*.go
      - internal/**/*.go
      - pkg/**/*.go
      - go.mod
      - go.sum
    generates:
      - bin/{{.BINARY_NAME}}
    preconditions:
      - sh: '{{if .CUDA}}[ -n "{{.CUDA_HOME_RESOLVED}}" ] && [ -d "{{.CUDA_LIBDIR}}" ] && [ -f "{{.CUDA_LIBDIR}}/libcudart.so" ] && [ -f "{{.CUDA_LIBDIR}}/libcublas.so" ]{{else}}true{{end}}'
        msg: 'CUDA toolkit libraries not found. Set CUDA_HOME or ensure nvcc is in PATH so "{{.CUDA_LIBDIR}}" resolves with libcudart.so and libcublas.so.'

  build:logdiff:
    desc: Build the logdiff tool
    cmds:
      - "{{.GO}} build -o bin/logdiff {{.BUILD_FLAGS}} ./cmd/logdiff"
    sources:
      - cmd/logdiff/**/*.go
      - internal/**/*.go
    generates:
      - bin/logdiff

  pack:
    desc: Pack a raw model into MCF format
    requires:
      vars: [MODEL_NAME]
    vars:
      INPUT_DIR: '{{.RAW_MODELS_DIR}}/{{.MODEL_NAME}}'
      OUTPUT_FILE: '{{.MCF_DIR}}/{{.MODEL_NAME}}.mcf'
    cmds:
      - 'bin/mantle pack -in "{{.INPUT_DIR}}" -out "{{.OUTPUT_FILE}}" --dedup --cast keep'
      - 'echo "Packed {{.OUTPUT_FILE}}"'
    preconditions:
      - sh: '[ -d "{{.INPUT_DIR}}" ]'
        msg: "Input directory {{.INPUT_DIR}} does not exist."

  quantize:
    desc: Quantize an existing MCF model (k4 by default)
    requires:
      vars: [MODEL_NAME]
    vars:
      INPUT_FILE: '{{.MCF_DIR}}/{{.MODEL_NAME}}.mcf'
      OUTPUT_FILE: '{{.MCF_DIR}}/{{.MODEL_NAME}}.k4.mcf'
    cmds:
      - 'bin/mantle quantize -in "{{.INPUT_FILE}}" -out "{{.OUTPUT_FILE}}" --method k4'
      - 'echo "Quantized to {{.OUTPUT_FILE}}"'
    preconditions:
      - sh: '[ -f "{{.INPUT_FILE}}" ]'
        msg: "Input file {{.INPUT_FILE}} not found."

  run:
    desc: Run a test prompt against a model
    requires:
      vars: [MODEL_NAME]
    vars:
      QUANT_SUFFIX: '{{.QUANT_SUFFIX | default ""}}'
      MODEL_FILE: '{{.MCF_DIR}}/{{.MODEL_NAME}}{{.QUANT_SUFFIX}}.mcf'
      BACKEND: '{{.BACKEND | default "auto"}}'
    cmds:
      - 'bin/{{.BINARY_NAME}} run --backend "{{.BACKEND}}" -m "{{.MODEL_FILE}}" --steps 128 --show-config --show-tokens --system "You are a helpful assistant." --prompt "In 100 words, tell me about you."'
    preconditions:
      - sh: '[ -f "{{.MODEL_FILE}}" ]'
        msg: "Model file {{.MODEL_FILE}} not found."
      - sh: '[ -x "bin/{{.BINARY_NAME}}" ]'
        msg: 'Binary bin/{{.BINARY_NAME}} not found. Build first with: task build{{if .CUDA}} CUDA=1{{end}}'

  inspect:
    desc: Inspect an MCF model container
    requires:
      vars: [MODEL_FILE]
    cmds:
      - 'bin/mantle inspect -m "{{.MODEL_FILE}}"'

  run:interactive:
    desc: Run in interactive mode
    vars:
      BACKEND: '{{.BACKEND | default "auto"}}'
    cmds:
      - 'bin/{{.BINARY_NAME}} run --backend "{{.BACKEND}}" --system "You are a helpful AI assistant."'
    preconditions:
      - sh: '[ -x "bin/{{.BINARY_NAME}}" ]'
        msg: 'Binary bin/{{.BINARY_NAME}} not found. Build first with: task build{{if .CUDA}} CUDA=1{{end}}'

  bench-simd-compare:
    desc: Run SIMD vs scalar benchmark comparisons
    cmds:
      - "{{.GO}} test -bench='(SIMD|Scalar)$' -benchtime=3s ./internal/tensor/"

  fmt:
    desc: Format all Go code
    cmds:
      - "{{.GO}} fmt ./..."

  test:
    desc: Run all tests
    cmds:
      - "{{.GO}} test ./..."

  lint:
    desc: Run golangci-lint with correct environment
    vars:
      TARGET_GOROOT:
        sh: '{{.GO}} env GOROOT'
    cmds:
      - 'GOROOT="{{.TARGET_GOROOT}}" PATH="{{.TARGET_GOROOT}}/bin:$PATH" golangci-lint run'
