version: "3"

vars:
  GO: go1.26rc2
  MODEL_NAME: "Qwen3-0.6B"

tasks:
  default:
    cmds:
      - task: build

  installGoRC:
    desc: Install Go 1.26rc2
    cmds:
      - go install golang.org/dl/go1.26rc2@latest
      - go1.26rc2 download
      - go1.26rc2 version

  build:
    env:
      GOEXPERIMENT: simd
    desc: Build the app and output the help text.
    cmds:
      - "{{.GO}} build -ldflags=\"-w -s\" -trimpath -o bin/mantle ./cmd/mantle"
      - echo "Successfully Built!"
    generates:
      - bin/mantle

  pack:
    env:
      MANTLE_PACK_OUT_DIR: /work/models/mcf
    desc: Pack a model into the model container format.
    cmds:
      - bin/mantle pack -in /work/models/raw/{{.MODEL_NAME}} -out /work/models/mcf/{{.MODEL_NAME}}.mcf --dedup --cast keep
      - echo "Successfully Packed MCF file!"
      - echo "You can now run the model using 'bin/mantle run -m /work/models/mcf/{{.MODEL_NAME}}.mcf'"

  quantize:
    env:
      MANTLE_QUANT_IN: /work/models/mcf/{{.MODEL_NAME}}.mcf
      MANTLE_QUANT_OUT: /work/models/mcf/{{.MODEL_NAME}}.k4.mcf
    desc: Quantize an existing MCF model (k4 by default).
    cmds:
      - bin/mantle quantize -in "$MANTLE_QUANT_IN" -out "$MANTLE_QUANT_OUT" --method k4
      - echo "Successfully Quantized MCF file!"

  run:
    env:
      MANTLE_MODELS_DIR: /work/models/mcf
    desc: Run a small test prompt against an MCF model.
    cmds:
      - |
        bin/mantle run -m "$MANTLE_MODELS_DIR/{{.MODEL_NAME}}.k4.mcf" \
          --steps 128 \
          --show-config \
          --show-tokens \
          --temp 0.1 \
          --top-k 40 \
          --top-p 0.9 \
          --min-p 0.05 \
          --rope-scale 1.0 \
          --rope-freq-base 1000000 \
          --system "You are a helpful assistant." \
          --prompt "In 100 words, tell me about you."

  run-interactive:
    env:
      MANTLE_MODELS_DIR: /work/models/mcf
    desc: Run in interactive mode
    cmds:
      - bin/mantle run --system "You are an all-knowing Artificial Intelligence"

  bench-simd-compare:
    env:
      GOEXPERIMENT: simd
    desc: Run SIMD vs scalar benchmark comparisons
    cmds:
      - "{{.GO}} test -bench='(SIMD|Scalar)$' -benchtime=3s ./internal/tensor/"

  fmt:
    env:
      GOEXPERIMENT: simd
    desc: Format all Go code
    cmds:
      - "{{.GO}} fmt ./..."

  test:
    env:
      GOEXPERIMENT: simd
    desc: Run all tests
    cmds:
      - "{{.GO}} test ./..."

  lint:
    cmds:
      - "GOROOT=$(GOEXPERIMENT=simd go1.26rc2 env GOROOT) PATH=\"$GOROOT/bin:$PATH\" GOEXPERIMENT=simd golangci-lint run"
