version: "3"

vars:
  GO: go1.26rc2

tasks:
  default:
    cmds:
      - task: build

  gguf_inspect:build:
    desc: Build the GGUF inspection tool
    cmds:
      - "{{.GO}} build -o bin/gguf_inspect ./cmd/gguf_inspect"
      - bin/gguf_inspect --help

  installGoRC:
    desc: Install Go 1.26rc2
    cmds:
      - go install golang.org/dl/go1.26rc2@latest
      - go1.26rc2 download
      - go1.26rc2 version

  build:
    env:
      GOEXPERIMENT: simd
    desc: Build the app using the latest Go 1.26 RC and output the help text.
    cmds:
      - "{{.GO}} build -ldflags=\"-w -s\" -trimpath -o bin/mantle ./cmd/mantle"
      - bin/mantle --help
    generates:
      - bin/mantle

  pack:
    env:
      MANTLE_PACK_OUT_DIR: /work/models/mcf
    desc: Pack a model into the model container format.
    cmds:
      - bin/mantle pack -in /work/models/raw/Ministral-3-3B-Instruct-2512-BF16 -out /work/models/mcf/Ministral-3-3B-Instruct-2512-BF16.mcf --dedup --cast keep

  run:
    env:
      MANTLE_MODELS_DIR: /work/models/mcf
    desc: Run a small test prompt against an MCF model.
    cmds:
      - |
        bin/mantle run -m "$MANTLE_MODELS_DIR/Ministral-3-3B-Instruct-2512-BF16.mcf" \
          --steps 128 \
          --show-config \
          --show-tokens \
          --system "You are an all-knowing Artificial Intelligence" \
          --prompt "Hello, this is a test prompt. In 100 words, tell me about you."

  run-interactive:
    env:
      MANTLE_MODELS_DIR: /work/models/mcf
    desc: Run in interactive mode
    cmds:
      - bin/mantle run --system "You are an all-knowing Artificial Intelligence"
